version: "3"
services:
  mlflow:
    image: python:3.8
    ports:
      - "5000:5000"
    environment:
      MLFLOW_SERVER_PORT: 5000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000  # Set MinIO endpoint URL
      MLFLOW_S3_IGNORE_TLS: "true"  # Ignore TLS for MinIO
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    depends_on:
      - postgres
      - minio  # Depend on MinIO service
    command: sh -c "pip install mlflow psycopg2-binary && apt-get update && apt-get install -y postgresql-client && mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri postgresql+psycopg2://\$POSTGRES_USER:\$POSTGRES_PASSWORD@\$POSTGRES_HOST:\$POSTGRES_PORT/\$POSTGRES_DB"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    ports:
      - "5432:5432"
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server /data
